version: '3.8'

services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 1111
      POSTGRES_DB: Deb2Spch
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    restart: always
    environment:
      DATABASE_URL: postgres://user:1111@db:5432/Deb2Spch?sslmode=disable
    depends_on:
      - db
    ports:
      - "3000:3000"
volumes:
  postgres_data: